all:         
	(cd dakota; make all)
	(cd templateSub; make all)

clean: 
	rm -f *~ *.o
	(cd dakota; make clean)

distclean: 
	(cd dakota; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
