all:         
	(cd openSeesInput; make all)
	(cd mdofBuildingModel; make all)

clean: 
	rm -f *~ *.o
	(cd openSeesInput; make clean)
	(cd mdofBuildingModel; make clean)

distclean: 
	(cd openSeesInput; make distclean)
	(cd mdofBuildingModel; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
