all:         
	(cd openSees; make all)
	(cd extractPGA; make all)

clean: 
	rm -f *~ *.o
	(cd openSees; make clean)
	(cd extractPGA; make clean)

distclean: 
	(cd openSees; make distclean)
	(cd extractPGA; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
