all:         
	(cd DEDM_HRP; make all)
	(cd multipleSimCenter; make all)
	(cd windTunnelExperiment; make all)
	(cd multiplePEER; make all)
	(cd stochasticGroundMotion; make all)
	(cd IsolatedBuildingCFD; make all)
	(cd stochasticWind; make all)
	(cd siteResponse; make all)


clean: 
	rm -f *~ *.o
	(cd DEDM_HRP; make clean)
	(cd multipleSimCenter; make clean)
	(cd LowRiseTPU; make clean)
	(cd windTunnelExperiment; make clean)
	(cd IsolatedBuildingCFD; make clean)
	(cd multiplePEER; make clean)
	(cd stochasticGroundMotion; make clean)
	(cd stochasticWind; make clean)
	(cd siteResponse; make clean)


distclean: 
	(cd DEDM_HRP; make distclean)
	(cd multipleSimCenter; make distclean)
	(cd LowRiseTPU; make distclean)
	(cd WindTunnelExperiment; make distclean)
	(cd IsolatedBuildingCFD; make distclean)
	(cd multiplePEER; make distclean)
	(cd stochasticGroundMotion; make distclean)
	(cd stochasticWind; make distclean)
	(cd siteResponse; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
