# Form implementation generated from reading ui file 'Node_Damage_Model_Window.ui'  # noqa: N999, D100
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Node_Damage_Model:  # noqa: N801, D101
    def setupUi(self, Node_Damage_Model):  # noqa: ANN001, ANN201, N802, N803, D102, PLR0915
        Node_Damage_Model.setObjectName('Node_Damage_Model')
        Node_Damage_Model.resize(396, 296)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Node_Damage_Model.setPalette(palette)
        self.buttonBox = QtWidgets.QDialogButtonBox(Node_Damage_Model)
        self.buttonBox.setGeometry(QtCore.QRect(300, 230, 81, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName('buttonBox')
        self.groupBox = QtWidgets.QGroupBox(Node_Damage_Model)
        self.groupBox.setGeometry(QtCore.QRect(20, 230, 261, 51))
        self.groupBox.setObjectName('groupBox')
        self.equal_emitter_button = QtWidgets.QRadioButton(self.groupBox)
        self.equal_emitter_button.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.equal_emitter_button.setChecked(True)
        self.equal_emitter_button.setObjectName('equal_emitter_button')
        self.equal_reservoir_button = QtWidgets.QRadioButton(self.groupBox)
        self.equal_reservoir_button.setGeometry(QtCore.QRect(120, 20, 131, 17))
        self.equal_reservoir_button.setObjectName('equal_reservoir_button')
        self.a_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.a_line.setGeometry(QtCore.QRect(40, 80, 41, 20))
        self.a_line.setObjectName('a_line')
        self.label = QtWidgets.QLabel(Node_Damage_Model)
        self.label.setGeometry(QtCore.QRect(20, 80, 21, 16))
        self.label.setObjectName('label')
        self.label_2 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 21, 16))
        self.label_2.setObjectName('label_2')
        self.label_3 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 21, 16))
        self.label_3.setObjectName('label_3')
        self.label_4 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 21, 16))
        self.label_4.setObjectName('label_4')
        self.label_5 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 21, 16))
        self.label_5.setObjectName('label_5')
        self.label_6 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 21, 16))
        self.label_6.setObjectName('label_6')
        self.b_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.b_line.setGeometry(QtCore.QRect(40, 100, 41, 20))
        self.b_line.setObjectName('b_line')
        self.c_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.c_line.setGeometry(QtCore.QRect(40, 120, 41, 20))
        self.c_line.setObjectName('c_line')
        self.d_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.d_line.setGeometry(QtCore.QRect(40, 140, 41, 20))
        self.d_line.setObjectName('d_line')
        self.e_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.e_line.setGeometry(QtCore.QRect(40, 160, 41, 20))
        self.e_line.setObjectName('e_line')
        self.f_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.f_line.setGeometry(QtCore.QRect(40, 180, 41, 20))
        self.f_line.setObjectName('f_line')
        self.label_10 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_10.setGeometry(QtCore.QRect(170, 80, 71, 20))
        self.label_10.setText('')
        self.label_10.setPixmap(QtGui.QPixmap(':/resources/resources/node_A.png'))
        self.label_10.setObjectName('label_10')
        self.label_11 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_11.setGeometry(QtCore.QRect(170, 100, 71, 20))
        self.label_11.setText('')
        self.label_11.setPixmap(QtGui.QPixmap(':/resources/resources/node_B.png'))
        self.label_11.setObjectName('label_11')
        self.label_12 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_12.setGeometry(QtCore.QRect(170, 120, 71, 20))
        self.label_12.setText('')
        self.label_12.setPixmap(QtGui.QPixmap(':/resources/resources/node_C.png'))
        self.label_12.setObjectName('label_12')
        self.label_13 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_13.setGeometry(QtCore.QRect(170, 140, 71, 20))
        self.label_13.setText('')
        self.label_13.setPixmap(QtGui.QPixmap(':/resources/resources/node_D.png'))
        self.label_13.setObjectName('label_13')
        self.label_14 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_14.setGeometry(QtCore.QRect(170, 160, 131, 20))
        self.label_14.setText('')
        self.label_14.setPixmap(QtGui.QPixmap(':/resources/resources/node_E.png'))
        self.label_14.setObjectName('label_14')
        self.label_15 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_15.setGeometry(QtCore.QRect(170, 180, 131, 20))
        self.label_15.setText('')
        self.label_15.setPixmap(QtGui.QPixmap(':/resources/resources/node_F.png'))
        self.label_15.setObjectName('label_15')
        self.label_16 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_16.setGeometry(QtCore.QRect(90, 180, 21, 16))
        self.label_16.setObjectName('label_16')
        self.aa_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.aa_line.setGeometry(QtCore.QRect(120, 80, 41, 20))
        self.aa_line.setObjectName('aa_line')
        self.label_17 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_17.setGeometry(QtCore.QRect(90, 120, 21, 16))
        self.label_17.setObjectName('label_17')
        self.ff1_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.ff1_line.setGeometry(QtCore.QRect(120, 180, 41, 20))
        self.ff1_line.setObjectName('ff1_line')
        self.cc_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.cc_line.setGeometry(QtCore.QRect(120, 120, 41, 20))
        self.cc_line.setObjectName('cc_line')
        self.label_18 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_18.setGeometry(QtCore.QRect(90, 80, 21, 16))
        self.label_18.setObjectName('label_18')
        self.label_19 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_19.setGeometry(QtCore.QRect(90, 100, 21, 16))
        self.label_19.setObjectName('label_19')
        self.bb_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.bb_line.setGeometry(QtCore.QRect(120, 100, 41, 20))
        self.bb_line.setObjectName('bb_line')
        self.ee1_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.ee1_line.setGeometry(QtCore.QRect(120, 160, 41, 20))
        self.ee1_line.setObjectName('ee1_line')
        self.dd_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.dd_line.setGeometry(QtCore.QRect(120, 140, 41, 20))
        self.dd_line.setObjectName('dd_line')
        self.label_20 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_20.setGeometry(QtCore.QRect(90, 160, 21, 16))
        self.label_20.setObjectName('label_20')
        self.label_21 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_21.setGeometry(QtCore.QRect(90, 140, 21, 16))
        self.label_21.setObjectName('label_21')
        self.ff2_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.ff2_line.setGeometry(QtCore.QRect(340, 180, 41, 20))
        self.ff2_line.setObjectName('ff2_line')
        self.ee2_line = QtWidgets.QLineEdit(Node_Damage_Model)
        self.ee2_line.setGeometry(QtCore.QRect(340, 160, 41, 20))
        self.ee2_line.setObjectName('ee2_line')
        self.label_22 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_22.setGeometry(QtCore.QRect(310, 180, 21, 16))
        self.label_22.setObjectName('label_22')
        self.label_23 = QtWidgets.QLabel(Node_Damage_Model)
        self.label_23.setGeometry(QtCore.QRect(310, 160, 21, 16))
        self.label_23.setObjectName('label_23')
        self.first_formula = QtWidgets.QLabel(Node_Damage_Model)
        self.first_formula.setGeometry(QtCore.QRect(20, 20, 361, 20))
        self.first_formula.setText('')
        self.first_formula.setPixmap(
            QtGui.QPixmap(':/resources/resources/first_damage.png')
        )
        self.first_formula.setObjectName('first_formula')
        self.second_formula = QtWidgets.QLabel(Node_Damage_Model)
        self.second_formula.setGeometry(QtCore.QRect(90, 40, 291, 20))
        self.second_formula.setText('')
        self.second_formula.setPixmap(
            QtGui.QPixmap(':/resources/resources/second_damage.png')
        )
        self.second_formula.setObjectName('second_formula')
        self.help_button = QtWidgets.QPushButton(Node_Damage_Model)
        self.help_button.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.help_button.setObjectName('help_button')

        self.retranslateUi(Node_Damage_Model)
        self.buttonBox.rejected.connect(Node_Damage_Model.reject)
        QtCore.QMetaObject.connectSlotsByName(Node_Damage_Model)

    def retranslateUi(self, Node_Damage_Model):  # noqa: ANN001, ANN201, N802, N803, D102
        _translate = QtCore.QCoreApplication.translate
        Node_Damage_Model.setWindowTitle(
            _translate('Node_Damage_Model', 'Node Damage Model')
        )
        self.groupBox.setTitle(_translate('Node_Damage_Model', 'Node Damage Type'))
        self.equal_emitter_button.setText(
            _translate('Node_Damage_Model', 'Equal Emitter')
        )
        self.equal_reservoir_button.setText(
            _translate('Node_Damage_Model', 'Equal Pipe & Reservoir')
        )
        self.label.setText(_translate('Node_Damage_Model', 'A'))
        self.label_2.setText(_translate('Node_Damage_Model', 'B'))
        self.label_3.setText(_translate('Node_Damage_Model', 'C'))
        self.label_4.setText(_translate('Node_Damage_Model', 'D'))
        self.label_5.setText(_translate('Node_Damage_Model', 'E'))
        self.label_6.setText(_translate('Node_Damage_Model', 'F'))
        self.label_16.setText(_translate('Node_Damage_Model', 'FF1'))
        self.label_17.setText(_translate('Node_Damage_Model', 'CC'))
        self.label_18.setText(_translate('Node_Damage_Model', 'AA'))
        self.label_19.setText(_translate('Node_Damage_Model', 'BB'))
        self.label_20.setText(_translate('Node_Damage_Model', 'EE1'))
        self.label_21.setText(_translate('Node_Damage_Model', 'DD'))
        self.label_22.setText(_translate('Node_Damage_Model', 'FF2'))
        self.label_23.setText(_translate('Node_Damage_Model', 'EE2'))
        self.help_button.setText(_translate('Node_Damage_Model', 'Help'))


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Node_Damage_Model = QtWidgets.QDialog()
    ui = Ui_Node_Damage_Model()
    ui.setupUi(Node_Damage_Model)
    Node_Damage_Model.show()
    sys.exit(app.exec_())
