all:         
	(cd standardEarthquakeEDP; make all)
	(cd standardEarthquakeEDP_R; make all)
	(cd standardWindEDP; make all)
	(cd standardEDP; make all)
	(cd userEDP; make all)
	(cd dummyEDP; make all)
	(cd gmtEDP; make all)
	(cd standardHydroEDP; make all)
	(cd standardTsunamiEDP; make all)
	(cd standardStormSurgeEDP; make all)

clean: 
	rm -f *~ *.o
	(cd standardEarthquakeEDP; make clean)
	(cd standardEarthquakeEDP_R; make clean)
	(cd standardWindEDP; make clean)
	(cd standardEDP; make clean)
	(cd userEDP; make clean)
	(cd dummyEDP; make clean)
	(cd gmtEDP; make clean)
	(cd standardHydroEDP; make clean)
	(cd standardTsunamiEDP; make clean)
	(cd standardStormSurgeEDP; make clean)

distclean: 
	(cd standardEarthquakeEDP; make distclean)
	(cd standardWindEDP; make distclean)
	(cd standardEDP; make distclean)
	(cd userEDP; make distclean)
	(cd dummyEDP; make distclean)
	(cd gmtEDP; make distclean)
	(cd standardHydroEDP; make distclean)
	(cd standardTsunamiEDP; make distclean)
	(cd standardStormSurgeEDP; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
