all:         
	(cd standardEarthquakeEDP; make all)
	(cd standardEarthquakeEDP_R; make all)
	(cd standardWindEDP; make all)
	(cd userEDP; make all)
	(cd gmtEDP; make all)

clean: 
	rm -f *~ *.o
	(cd standardEarthquakeEDP; make clean)
	(cd standardEarthquakeEDP_R; make clean)
	(cd standardWindEDP; make clean)
	(cd userEDP; make clean)
	(cd gmtEDP; make clean)

distclean: 
	(cd standardEarthquakeEDP; make distclean)
	(cd standardWindEDP; make distclean)
	(cd userEDP; make distclean)
	(cd gmtEDP; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
