all:
	(cd regionalWindField; make all)


clean:
	rm -f *~ *.o
	(cd regionalWindField; make clean)


distclean:
	(cd regionalWindField; make distclean)

# DO NOT DELETE THIS LINE -- make depend depends on it.
